---
title: "R & Python"
author: "Kiko"
date: "1/7/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reticulate

```{r}
library(reticulate)
use_python("C:/ProgramData/Anaconda3/envs/CursoEstadisticaDescriptiva/python.exe")

os <- import("os")
x <- os$listdir(".")

matrix(x, length(x))
```


```{r}
np <- import("numpy", convert = FALSE)

x <- np$array(c(1:4))
sum <- x$cumsum()

print(sum)

py_to_r(sum)
```

## Ayuda

El resultado de $i^2$:
```{python, results='asis'}
from sympy import *
for i in range(10):
  print("$"+latex(str(pow(i,2)))+"$")
```


## Arrays


```{r}
datos <- iris
head(datos)
datos_py <- r_to_py(datos)
```


```{python}
import numpy as np
import pandas as pd

r.datos_py.head()
```


```{r}
library(Matrix)
N <- 6
sparse_mat <- sparseMatrix(
  i = sample(N, N, replace = F),
  j = sample(N, N, replace = F),
  x = runif(N),
  dims = c(N, N)
)
sparse_mat
sparse_mat_py <- r_to_py(sparse_mat)
```

```{python}
print(r.sparse_mat_py)
```


$$\left(\frac{2}{3}\right)^2\cdot\left(\frac{\frac{3}{2}}{\frac{\alpha}{\beta}}\right)+\gamma \le \epsilon$$
