---
title: "Matrices"
author: "Kiko"
date: "5/7/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Matrices (1ª parte)

```{r}
M = matrix(1:12, nrow=4)
M
M = matrix(1:12, nrow=4, byrow = T)
M
M = matrix(1:12, nrow=3)
M
M = matrix(1:12, nrow=5)
M
M = matrix(1, nrow = 4, ncol = 6)
M
```

### Ejercicio

```{r}
M = matrix(0, nrow = 3, ncol = 5)
M
vec = 1:12
M = matrix(vec, nrow = 3)
M
```

## Matrices (2ª parte)

```{r}
M = rbind(M, c(1,2,3,4), -4:-1)
M
M = cbind(M, seq(0, 100, length.out = 5))
M
M_diag = diag(1:9)
M_diag
```

## Propiedades matrices

```{r}
m = matrix(1:20, nrow = 4)
m
diag(m)
nrow(m)
ncol(m)
dim(m)
sum(m)
prod(m)
mean(m)
colSums(m)
rowSums(m)
colMeans(m)
rowMeans(m)
apply(m, MARGIN = 1, FUN = function(x){sqrt(sum(x^2))})
apply(m, MARGIN = 2, FUN = function(x){sqrt(sum(x^2))})
apply(m, MARGIN = c(1,2), FUN = function(x){x^2})
```

## Repaso álgebra lineal (1ª parte)

```{r}
m = matrix(0:99, nrow = 10)
m
tm = t(m)
tm
m + tm
m * tm
m %*% tm
library(Biodem)
mtx.exp(m, 2)
library(Matrix)
library(expm)
tm %^% 2
```

### Ejercicio

Si $A=\begin{pmatrix}2 & 0 & 2\\1 & 2 & 3\\0 & 1 & 3\end{pmatrix}$ y $B=\begin{pmatrix}3 & 2 & 1\\1 & 0 & 0\\1 & 1 & 1\end{pmatrix}$, calcular $A \cdot B$, $A^2$ y $B^3$

```{r}
A = matrix(c(2, 0, 2, 1, 2, 3, 0, 1, 3), nrow = 3, byrow = TRUE)
B = matrix(c(3, 2, 1, 1, 0, 0, 1, 1, 1), nrow = 3, byrow = TRUE)
A * B
A %*% A
B %*% B %*% B
```


## Repaso álgebra lineal (2ª parte)

```{r}
library(magic)
m = magic(3)
m
det(m)
qr(m)
qr(m)$rank
solve(m) # Inversa de la matriz
solve(m, c(1, 2, 3)) # Resuelve sistema de ecuaciones
eigen(m)
eigen(m)$values
eigen(m)$vectors
```

### Ejercicio

Si $M=\begin{pmatrix}2 & 6 & -8\\0 & 6 & -3\\0 & 2 & 1\end{pmatrix}$ comprobar que $M=P \cdot D \cdot P^{-1}$

```{r}
M = rbind(c(2,6,-8), c(0,6,-3), c(0,2,1))
M
P = eigen(M)$vectors
P
D = diag(eigen(M)$values)
D
Pinv = solve(P)
Pinv
P%*%D%*%Pinv
```

## Repaso álgebra lineal (3ª parte)

```{r}
A = matrix(c(3-2i, 5+3i, 1+2i, 2-1i), nrow = 2, byrow = T)
A
A%*%A
eigen(A)
solve(A, c(1-1i, 4))
prod(eigen(A)$values) # det(A)
```